exclude: 'venv|migrations'
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.0.1
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: check-added-large-files
  - id: debug-statements
  - id: check-toml
  - id: check-ast
  - id: check-case-conflict
- repo: https://github.com/pycqa/flake8
  rev: 3.9.2
  hooks:
  - id: flake8

- repo: https://github.com/pycqa/isort
  rev: 5.9.1
  hooks:
  - id: isort

- repo: https://github.com/wemake-services/dotenv-linter
  rev: 0.2.0
  hooks:
    - id: dotenv-linter

- repo: https://github.com/PyCQA/bandit
  rev: 1.7.0
  hooks:
    - id: bandit
      args: ['--skip', 'B101']

- repo: local
  hooks:
    - id: migrations-check
      language: system
      name: Check for uncreated migrations.
      entry: sh -c "./api/manage.py makemigrations --check --dry-run"
      files: models/*.*\.py$
      stages: [commit]
