# Generated by Django 3.2.4 on 2021-07-10 21:39

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(blank=True, max_length=254, null=True)),
                ('overview_url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CaseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(blank=True, max_length=254, null=True)),
                ('can_be_stattrack', models.BooleanField(default=False)),
                ('grade', models.CharField(blank=True, choices=[('Mil-spec', 'Mil-spec'), ('Restricted', 'Restricted'), ('Classified', 'Classified'), ('Covert', 'Covert'), ('Special', 'Special')], max_length=20, null=True)),
                ('exterior', models.CharField(blank=True, choices=[('Well-Worn', 'Well-Worn'), ('Battle-Scarred', 'Battle-Scarred'), ('Field-Tested', 'Field-Tested'), ('Minimal Wear', 'Minimal Wear'), ('Factory New', 'Factory New')], max_length=20, null=True)),
                ('is_stattrack', models.BooleanField(default=False)),
                ('general_item_probability', models.FloatField(blank=True, default=0, null=True)),
                ('probability', models.FloatField(blank=True, default=0, null=True)),
                ('case', models.ManyToManyField(related_name='case_item', to='cases.Case')),
            ],
        ),
        migrations.AddConstraint(
            model_name='case',
            constraint=models.UniqueConstraint(fields=('name',), name='unique case name'),
        ),
        migrations.AddConstraint(
            model_name='caseitem',
            constraint=models.UniqueConstraint(fields=('grade', 'name', 'is_stattrack', 'exterior'), name='unique case item'),
        ),
    ]
